name: althafapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.5
  intl: ^0.18.0
  permission_handler: ^11.4.0
  fluttertoast: ^8.2.12
  flutter_native_splash: ^2.4.4
  provider: ^6.1.4
  collection: ^1.19.0
  flutter_credit_card: ^4.1.0
  shared_preferences: ^2.2.2 # Use latest version


dev_dependencies:
  flutter_test:
   sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/image/


 
flutter_native_splash:
 color: "#FFFFF" # background color of splash screen
 image: lib/image/person.png # your splash image (put it inside assets folder)
 android: true
 ## ios: true




 

